pipeline {

    agent any

    stages {

        stage('Build') {
            steps {
                sh '''
                    ./pipeline/jenkins/build/build.sh
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh './pipeline/jenkins/deploy/deploy.sh'
            }
        }
    }
}