pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                sh "chmod +x -R ${env.WORKSPACE}"
                sh './pipeline/jenkins/build/build.sh'

            }
        }

        stage('Deploy') {
            steps {
                sh "chmod +x -R ${env.WORKSPACE}"
                sh './pipeline/jenkins/deploy/deploy.sh'
            }
        }
    }
}