spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id:
            client-secret:
            client-name:
            authorization-grant-type:
            redirect-uri:
            client-authentication-method:
            scopt:
              -
              -

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  # jwt secret key
  jwt:
    secret:

  # auth : for normal user | oauth2 : for kakao user
  app:
    auth:
      token-secret:
      token-expiry:
      refresh-token-expiry:
    oauth2:
      authorized-redirect-uris: